run-pipeline:
	    mvn compile exec:java -Dexec.mainClass=com.peppysisay.ChatAnalysisPipeline \
	        -Dexec.args="--runner='DirectRunner' --inputSchemaPath='/Users/peppysisay/playground/chat-analysis-pipeline/beam/schemas/pubsub.json' --outputSchemaPath='/Users/peppysisay/playground/chat-analysis-pipeline/beam/schemas/output.json'"
install:
	    mvn install
